version: 2
updates:
  - directory: /gentei
    package-ecosystem: gomod
    open-pull-requests-limit: 1
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
