apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 100%
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: web
          image: ghcr.io/member-gentei/gentei:latest
          args:
            - serve
            - "--address"
            - ":5000"
            - "--discord-redirect-url"
            - "https://gentei.tindabox.net/login/discord"
          env:
            - name: DISCORD_CLIENT_ID
              value: "768486576388177950"
          envFrom:
            - secretRef:
                name: gentei-db
            - secretRef:
                name: gentei-web
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
