name: prod

on:
  push:
    branches:
      - "main"

defaults:
  run:
    working-directory: gentei

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: "arm64"
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker buildx
        run: |
          docker build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/member-gentei/gentei:${{ github.sha }} \
            --tag ghcr.io/member-gentei/gentei:latest \
            --push \
            .
          docker tag gentei ghcr.io/member-gentei/gentei:${{ github.sha }}
          docker tag gentei ghcr.io/member-gentei/gentei:latest
      - name: docker push
        run: |
          docker push ghcr.io/member-gentei/gentei:${{ github.sha }}
          docker push ghcr.io/member-gentei/gentei:latest
  deploy:
    needs: docker
    runs-on: self-hosted
    defaults:
      run:
        working-directory: gentei/_k8s
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v2.0
      - uses: imranismail/setup-kustomize@v1
      - name: kustomize
        run: |
          kustomize edit set image ghcr.io/member-gentei/gentei=ghcr.io/member-gentei/gentei:${{ github.sha }}
      - run: kubectl -n gentei apply -k .
